### ISSUE TITLE
Instance will cause RMClientAT.init to execute twice

### ISSUE THREAD

**Issue by hxliujing** [alibaba/fescar#101]
Once in the main method
// 一次是main 方法里面

>  String applicationId = "dubbo-demo-account-service";
>         String txServiceGroup = "my_test_tx_group";
>         RMClientAT.init(applicationId, txServiceGroup);

Once is the xml inside GlobalTransactionScanner
// 一次是xml 里面GlobalTransactionScanner

> if ((AT_MODE & mode) > 0) {
            RMClientAT.init(applicationId, txServiceGroup);

Will cause the AsyncWorker.init() method timerExecutor to be created 2 times and call the doBranchCommits() method.
// 会造成AsyncWorker.init()方法timerExecutor 创建2次，并调用doBranchCommits()方法

The author intended that the RMClient could be created by code or xml's GlobalTransactionScanner method, but the document did not specify the information.
// 作者本意是可以通过代码或者xml 的GlobalTransactionScanner方式去创建RMClient，但是文档没有说明该条信息

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
Fixed by https://github.com/alibaba/fescar/pull/104
