### ISSUE TITLE
应该去除SQLVisitorFactory.main方法

### ISSUE THREAD

**Issue by hxliujing** [alibaba/fescar#114]
`public static void main(String[] args) throws Throwable {
        String sql = "update material_inventory SET version = ? WHERE is_deleted = 0 and id = ? and version = ?";

        for (int i=0; i<100; i++) {
            long begin = System.currentTimeMillis();
            SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);
            long end = System.currentTimeMillis();
            System.out.println(String.format("SQL:[%s] parser too slow, cost [%d] ms.", sql, (end - begin)));
        }

    }`

**Comment by slievrly** [comment]
@hxliujing can you proposal an PR?
