### ISSUE TITLE
FileTransactionStoreManager#closeFile() method internal fileChannel.close() is redundant

### ISSUE THREAD

**Issue by ykgarfield** [alibaba/fescar#127]
`FileTransactionStoreManager#closeFile()` method implement is first invoke `FileChannel.close()` then invoke `RandomAccessFile.close()`.

According `RandomAccessFile#close()`  source code, it will auto close channel, so there is no need to invoke `FileChannel.close()`.

**RandomAccessFile#close()**  method:

```java
public void close() throws IOException {
	...
	if (channel != null) {
		channel.close();
	}
	...
}
```

**FileTransactionStoreManager#closeFile()** method:

```java
private void closeFile(RandomAccessFile raf, FileChannel fileChannel) {
        // this code can remove
	if (null != fileChannel) {
		fileChannel.close();
		fileChannel = null;
	}
	if (null != raf) {
		raf.close();
		raf = null;
	}
}
```

**Comment by slievrly** [comment]
Seeing that you submitted a lot of questions, why not try to be contributor ？@ykgarfield
