### ISSUE TITLE
求中文文档！

### ISSUE THREAD

**Issue by dslchd** [alibaba/fescar#17]
明明是国人开发的框架，却连个中文文档都没有，这一点与dubbo差远了。

**Comment by nicky-chen** [comment]
这么简单的英文

**Comment by sharajava** [comment]
wiki in Chinese will surely be released soon. sorry about the lack of doc.

**Comment by guochangFree** [comment]
建议还是学习下英文。。。。

**Comment by dslchd** [comment]
> 建议还是学习下英文。。。。

这跟我学不学英文是两码事，你搞清楚，我并不是看不懂，ok?

**Comment by dslchd** [comment]
closed
