### ISSUE TITLE
Test case should be added to enhance the test coverage

### ISSUE THREAD

**Issue by slievrly** [alibaba/fescar#195]
### Requirement: 

Test case should be added to enhance the test coverage . Junit and mockito can be used as  test framework.
  Welcome everyone to join in，you can comment on the issue that you're interest with.

### Project address 
  https://github.com/alibaba/fescar/projects/1

##  Issues
 
|status | assignee                                                 | issues            |
| ------------------------------------------------------------ | ------------- | ------ |
|     |       |  [Add unit test to fescar-common module](https://github.com/alibaba/fescar/issues/187) |
|     |       |  [Add unit test to fescar-config module](https://github.com/alibaba/fescar/issues/188)|
|     | @xiajunhust  |  [Add unit test to fescar-core module](https://github.com/alibaba/fescar/issues/189)|
|     |       |  [Add unit test to fescar-dubbo module](https://github.com/alibaba/fescar/issues/190)|
|     |       |  [Add unit test to fescar-rm-datasource module](https://github.com/alibaba/fescar/issues/191)|
|     |       |  [Add unit test to fescar-server module](https://github.com/alibaba/fescar/issues/192)|
|     |     @tswstarplanet  |  [Add unit test to fescar-spring module](https://github.com/alibaba/fescar/issues/193)|
|     |       |  [Add unit test to fescar-tm module](https://github.com/alibaba/fescar/issues/194)|

**Comment by gzlicanyi** [comment]
I didn't find the standard create table SQL statement in the documentation or the code, including undo_log, account_tbl, storage_tbl, and order_tbl, so please provide it, and not others who want to help must guess it from the code.

**Comment by slievrly** [comment]
It is included in the quickstart and will be added to the demo script later.

**Comment by slievrly** [comment]
UnitTest Must contain copyright
