### ISSUE TITLE
spring cloud可不可以用?

### ISSUE THREAD

**Issue by ylh23y** [alibaba/fescar#20]
spring cloud可不可以用?

**Comment by huangll99** [comment]
同问，有没有计划支持spring cloud

**Comment by ifzm** [comment]
同问

**Comment by sharajava** [comment]
Welcome get involved in Fescar for working with Spring Cloud. Supporting Spring Cloud is surely in our roadmap. It's will be very nice if you can try a demo or solution. 👍 Or at least, you can share you use cases in detail.

**Comment by venbill** [comment]
+1

**Comment by objcoding** [comment]
+1

**Comment by objcoding** [comment]
@sharajava 大佬, 这必须得支持SpringCloud啊!

**Comment by myhgc** [comment]
目前还没支持Spring Cloud么

**Comment by szlzhm** [comment]
springclud 版本什么时候发布？

**Comment by flystar32** [comment]
you can refer to this issue and  repository, https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/303

**Comment by jacksparrow414** [comment]
我看官方setea的网站上关于spring的支持板块目前基本上TBD，希望能尽快补上呢
