### ISSUE TITLE
能不能搞1个spring cloud的调用使用demo？

### ISSUE THREAD

**Issue by duyishuaixue** [alibaba/fescar#22]
（1）能不能搞1个spring cloud的调用使用demo？
（2）可以使用微服务的分布式事务吗？

**Comment by 67570700** [comment]
Does it support spring cloud?

**Comment by xqq1994** [comment]
0.5.0 version will support

**Comment by xingfudeshi** [comment]
try samples here:https://github.com/fescar-group/fescar-samples
