### ISSUE TITLE
When retrying rollback of global session failed, the status of the Global Session is wrong

### ISSUE THREAD

**Issue by tankilo** [alibaba/fescar#266]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
At com.alibaba.fescar.server.coordinator.DefaultCore#doGlobalRollback,
when the BranchRollbackRequest from TC to RM failed ( RM hang ),   RM channel will be destroyed and globalSession will be added to retry queue.

When retrying at com.alibaba.fescar.server.coordinator.DefaultCore#doGlobalRollback, 
TC will ask one of other RMs with the same resources (ChannelManager#getChannel) to help dealing BranchRollbackRequest.

If success, then global session status will be Rollbacked.
But if failure, global session will still be Rollbacked instead of RollbackFailed or somethings else.

### Ⅱ. Describe what happened

![image](https://user-images.githubusercontent.com/10413284/51665349-8678f280-1ff6-11e9-9243-6be4f4a31b89.png)

you can see, GlobalSession#branchSessions is not null ,but status is Rollbacked

### Ⅲ. Describe what you expected to happen
If failure, global session will still be RollbackFailed.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
Before entering com.alibaba.fescar.server.coordinator.DefaultCoordinator#handleRetryRollbacking, turn all the RM down.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by tankilo** [comment]
I am trying to fork the project and make a pull request.

**Comment by sharajava** [comment]
Great found and very good fix. 👍
