### ISSUE TITLE
Contact 链接错误

### ISSUE THREAD

**Issue by gqipan** [alibaba/fescar#27]
![image](https://user-images.githubusercontent.com/13899316/50964983-acd56300-150b-11e9-8549-b8db1c51e66d.png)

![image](https://user-images.githubusercontent.com/13899316/50965047-dc846b00-150b-11e9-9a05-0cd3e6c35c25.png)

![image](https://user-images.githubusercontent.com/13899316/50965062-e1491f00-150b-11e9-9c3f-04e0f1ce460b.png)

Contact: Segmentfault 和 Gitter 打不开

**Comment by jsbxyyx** [comment]
@gqipan 不是写了TBD吗

**Comment by sharajava** [comment]
👍 thank you. will update it later.
