### ISSUE TITLE
 ask a question. If the commit timeout, how to determine whether the transaction is successful, how to deal with this transaction?

### ISSUE THREAD

**Issue by walterzhaoJR** [alibaba/fescar#279]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

 ask a question. If the commit timeout, how to determine whether the transaction is successful, how to deal with this transaction?

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by sharajava** [comment]
There is a getStatus API in TransactionManager. Commonly, applications should check status later, and try to commit again if the status is still BEGIN.

**Comment by walterzhaoJR** [comment]
OK,i see.THX
