### ISSUE TITLE
On windows the fescar-server.bat use $EXTRA_JVM_ARGUMENTS has error

### ISSUE THREAD

**Issue by zhong15** [alibaba/fescar#302]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

On Windows the fescar-server.bat used $EXTRA_JVM_ARGUMENTS variable has an error

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
错误: 找不到或无法加载主类 $EXTRA_JVM_ARGUMENTS
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. On windows run the bin/fescar-server.bat

### Ⅵ. Environment:

- JDK version : 1.8.0_201
- OS : Windows 10
- Others: fescar-server-0.1.2

**Comment by xingfudeshi** [comment]
Please close this issue as the related bug has been fixed.
