### ISSUE TITLE
TransactionalTemplate#execute doesn't call GlobalTransactionContext#clean, which result in leaking ThreadLocal variables

### ISSUE THREAD

**Issue by tankilo** [alibaba/fescar#313]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
TransactionalTemplate#execute doesn't call GlobalTransactionContext#clean, which result in leaking ThreadLocal variables

### Ⅱ. Describe what happened
First method call
![image](https://user-images.githubusercontent.com/10413284/51822818-60b25d00-2318-11e9-8b4c-48fc4da96375.png)

Second method call, the xid that leaked by the first method call can still be achieved!!!
![image](https://user-images.githubusercontent.com/10413284/51822838-6dcf4c00-2318-11e9-81d2-261bcca7fbbd.png)

![image](https://user-images.githubusercontent.com/10413284/51823198-acb1d180-2319-11e9-8568-82a2e41f038e.png)

### Ⅲ. Describe what you expected to happen
After exiting method TransactionalTemplate#execute, any ThreadLocal variables of the global transaction which are newly created by this method call should be cleared.    
Just like Spring JDBC, the outside transaction aop method should clean up the resources that it created.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
I have a project [fescar-test](https://github.com/tankilo/fescar-test),  you need to edit [Simple.java](https://github.com/tankilo/fescar-test/blob/master/fescar-test-simple/src/main/java/com/tankilo/Simple.java) first to bypass https://github.com/alibaba/fescar/issues/312

![image](https://user-images.githubusercontent.com/10413284/51822926-b8e95f00-2318-11e9-8ce7-d4cb0bda1538.png)

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by sharajava** [comment]
Could you please give a reproducing steps for this issue?

**Comment by tankilo** [comment]
> Could you please give a reproducing steps for this issue?
please check [README.md](https://github.com/tankilo/fescar-test/blob/master/README.md) in my project.

**Comment by shanbing** [comment]
I use it in spring boot enviroment,this is happend too,because tomcat use thread pool.
I think it should clean when method DefaultGlobalTransaction#clean and commit.

**Comment by tankilo** [comment]
https://github.com/alibaba/fescar/issues/325  Bring new probelms in nested transaction scenes!!!

Please check section [fescar-test-nestedsession
] in my [project](https://github.com/tankilo/fescar-test/blob/master/README.md)

![image](https://user-images.githubusercontent.com/10413284/51955604-64acbf00-247f-11e9-9b1f-07b49ffb8838.png)


Inner transaction will commit the outside transaction, though they are the same transaction, the commit or rolllback of the global transaction should be done by the outside transaction.
![image](https://user-images.githubusercontent.com/10413284/51955496-10a1da80-247f-11e9-9a35-aae37350076d.png)
![image](https://user-images.githubusercontent.com/10413284/51955614-6a0a0980-247f-11e9-8383-01b0ae954b53.png)

When the outside transaction come back to rollback, the undo_log has already been cleared by the inner transaction.
![image](https://user-images.githubusercontent.com/10413284/51955579-4c3ca480-247f-11e9-9f8a-a6b9f3442ccc.png)

![image](https://user-images.githubusercontent.com/10413284/51955590-56f73980-247f-11e9-906b-03c0287fd87a.png)
![image](https://user-images.githubusercontent.com/10413284/51955594-59f22a00-247f-11e9-811c-8c184391fd66.png)
