### ISSUE TITLE
About UNDO_LOG table

### ISSUE THREAD

**Issue by jingzhouzhao** [alibaba/fescar#32]
The same db used by the three services in the demo, in the actual application, whether the db corresponding to each service needs to create UNDO_LOG table?
// demo中三个service使用的同一个db，在实际应用中，是否每个service对应的db都需要create UNDO_LOG table?

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by sharajava** [comment]
Yes, every db involved in Fescar managed distributed transaction should have a  undo_log table.
