### ISSUE TITLE
have a coding standard problem

### ISSUE THREAD

**Issue by as378341313** [alibaba/fescar#322]
我有一个代码规范问题：在fescar的源码中，NettyServerConfig 继承了NettyBaseConfig这个类，在NettyBaseConfig中已经有了一个成员变量Configuration CONFIG，为什么在它子类的时候又要继续添加上这样一个成员变量，不能直接使用父类的就好吗
在父类NettyBaseConfig中的成员变量：
 protected static final Configuration CONFIG = ConfigurationFactory.getInstance();
在子类NettyServerConfig中的成员变量：
  private static final Configuration CONFIG = ConfigurationFactory.getInstance();

**Comment by slievrly** [comment]
@as378341313 I will fix this problem，thank you。
