### ISSUE TITLE
Reporting bugs url is wrong

### ISSUE THREAD

**Issue by smileMrLee** [alibaba/fescar#34]
“Reporting bugs
Please follow the [template](https://github.com/TBD) for reporting any issues.”

This “template” url is wrong

![image](https://user-images.githubusercontent.com/10806592/51009407-08930100-158b-11e9-910d-c75c3025b193.png)

**Comment by sharajava** [comment]
Sorry for the trouble. Actually, template for bug reporting is not ready yet. Will surely update the link later. Thanks 👍 

You can just report bugs with [bug] or [bug report] label at the beginning of the issue's title.
