### ISSUE TITLE
Can xid of transaction be "" ?

### ISSUE THREAD

**Issue by tswstarplanet** [alibaba/fescar#35]
I read the code of global transaction and I found the xid can be "", I think it’s not right ?

**Comment by slievrly** [comment]
is sample print out like “ Main business begin ... xid: null” ，if like this，it's right.

**Comment by tswstarplanet** [comment]
If the xid is "", how to use it to trace one transaction ？

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/51012831-2ae04b00-159a-11e9-969e-f6402a35fc89.png)
