### ISSUE TITLE
suggest move buildUndoItem and buildLockKey  from ConnectionProxy to Executor

### ISSUE THREAD

**Issue by masterfengj** [alibaba/fescar#352]
## Why you need it?

buildUndoItem and buildLockKey  maybe depency with some detail of sql executing enviroment, eg sql hints, so suggest do it in Executor, eg BaseTransactionalExecutor
and then ConnectionProxy's duties was pure and simple, eg simply provide:   appendUndoItem(SQLUndoLog log) and checkLock(String lockKey)

**Comment by xingfudeshi** [comment]
please close this issue as the related problem has been fixed.
