### ISSUE TITLE
Metrics Desgin

### ISSUE THREAD

**Issue by zhengyangyong** [alibaba/fescar#364]
Hello, I had read fescar roadmap and found that `Metrics` in it ,here is my idea:

### Module:

![default](https://user-images.githubusercontent.com/374335/52390220-3dcf3800-2ad2-11e9-9dfd-5dcf14972d63.png)

- fescar-metrics: basic metrics api module without implement,include interface of`Gauge`,`Counter`,`Timer`,`Histogram`,`Registry`,`Publisher` etc... we can implement them with many components such as [spectator](http://netflix.github.io/spectator/en/latest/), [dropwizard metrics](https://metrics.dropwizard.io/4.0.0/getting-started.html), and publish metrics data to [prometheus](https://prometheus.io/docs/introduction/overview/), zabbix etc...
- fescar-metrics-prometheus: metrics implement with a simple meter implement and publish to  prometheus for default scenario, will implement as higher formance as possible and reduce the resource usage.

### How Metrics Module Load:
Will use `EnhancedServiceLoader` not Spring because Spring will remove at v1.5.x, so whether metrics is enabled depends on any metrics implement module is imported.

### Default Export Metrics:
TC:
1. fescar.transaction(role=tc,meter=gauge,status=active) : current active transaction number 
2. fescar.transaction(role=tc,meter=counter,status=committed/rollback) : total committed/rollback transaction count
3. fescar.transaction(role=tc,meter=histogram,statistic=total,status=committed/rollback) : current cycle(window time) committed/rollback transaction count
4. fescar.transaction(role=tc,meter=histogram,statistic=count,status=committed/rollback) :  current cycle(window time) committed/rollback transaction count, *because each transaction only inc 1, so will equal with total*
5. fescar.transaction(role=tc,meter=histogram,statistic=tps,status=committed/rollback) : current cycle(window time) committed/rollback transaction per second, **not export default because can compute it with count / cycle(window time)**
6. fescar_transaction(role=tc,meter=timer,statistic=total,status=committed/rollback) : current cycle(window time) committed/rollback total transaction milliseconds 
7. fescar_transaction(role=tc,meter=timer,statistic=count,status=committed/rollback) : current cycle(window time) committed/rollback transaction count
8. fescar_transaction(role=tc,meter=timer,statistic=average,status=committed/rollback) : current cycle(window time) committed/rollback average transaction milliseconds, **not export default because can compute it with total / count**
9. fescar_transaction(role=tc,meter=timer,statistic=max,status=committed/rollback) : current cycle(window time) committed/rollback max transaction milliseconds

TM:
coming soon.. , such as
fescar.transaction(role=tm,name={GlobalTransactionalName},meter=gauge,status=active) : current active transaction number separated by transaction name

RM:
coming soon.. , such as 
fescar.transaction(role=rm,name={BranchTransactionalName},mode=at/mt,meter=gauge,status=active) : current active branch transaction number separated by transaction name

**Comment by slievrly** [comment]
@

> Hello, I had read fescar roadmap and found that `Metrics` in it ,here is my idea:
> 
> ### Module:
> ![default](https://user-images.githubusercontent.com/374335/52390220-3dcf3800-2ad2-11e9-9dfd-5dcf14972d63.png)
> 
> * fescar-metrics: basic metrics api module without implement,include interface of`Gauge`,`Counter`,`Timer`,`Histogram`,`Registry`,`Publisher` etc... we can implement them with many components such as [spectator](http://netflix.github.io/spectator/en/latest/), [dropwizard metrics](https://metrics.dropwizard.io/4.0.0/getting-started.html), and publish metrics data to [prometheus](https://prometheus.io/docs/introduction/overview/), zabbix etc...
> * fescar-metrics-prometheus: metrics implement with a simple meter implement and publish to  prometheus for default scenario, will implement as higher formance as possible and reduce the resource usage.
> 
> ### How Metrics Module Load:
> Will use `EnhancedServiceLoader` not Spring because Spring will remove at v1.5.x, so whether metrics is enabled depends on any metrics implement module is imported.
> 
> ### Default Export Metrics:
> TC:
> 
> 1. fescar.transaction(role=tc,meter=gauge,status=active) : current active transaction number
> 2. fescar.transaction(role=tc,meter=counter,status=committed/rollback) : total committed/rollback transaction count
> 3. fescar.transaction(role=tc,meter=histogram,statistic=total,status=committed/rollback) : current cycle(window time) committed/rollback transaction count
> 4. fescar.transaction(role=tc,meter=histogram,statistic=count,status=committed/rollback) :  current cycle(window time) committed/rollback transaction count, _because each transaction only inc 1, so will equal with total_
> 5. fescar.transaction(role=tc,meter=histogram,statistic=tps,status=committed/rollback) : current cycle(window time) committed/rollback transaction per second, **not export default because can compute it with count / cycle(window time)**
> 6. fescar_transaction(role=tc,meter=timer,statistic=total,status=committed/rollback) : current cycle(window time) committed/rollback total transaction milliseconds
> 7. fescar_transaction(role=tc,meter=timer,statistic=count,status=committed/rollback) : current cycle(window time) committed/rollback transaction count
> 8. fescar_transaction(role=tc,meter=timer,statistic=average,status=committed/rollback) : current cycle(window time) committed/rollback average transaction milliseconds, **not export default because can compute it with total / count**
> 9. fescar_transaction(role=tc,meter=timer,statistic=max,status=committed/rollback) : current cycle(window time) committed/rollback max transaction milliseconds
> 
> TM:
> coming soon.. , such as
> fescar.transaction(role=tm,name={GlobalTransactionalName},meter=gauge,status=active) : current active transaction number separated by transaction name
> 
> RM:
> coming soon.. , such as
> fescar.transaction(role=rm,name={BranchTransactionalName},mode=at/mt,meter=gauge,status=active) : current active branch transaction number separated by transaction name

@zhengyangyong Currently Metrics has not been designed, if you are interested, you can ping me.

**Comment by zhengyangyong** [comment]
OK, I will send mail to you, best regards
