### ISSUE TITLE
Because the network is interrupted, the network is flashing, the node is down, the timeout is abnormal, and the framework is compensated.

### ISSUE THREAD

**Issue by zxj19951029** [alibaba/fescar#37]
Because the network is interrupted, the network is flashing, the node is down, the timeout is abnormal, and the framework has compensation measures?
// 因为网络中断，网张闪断，节点宕机，超时情况，产生的异常，框架有补偿措施吗？

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by sharajava** [comment]
Yes. Status change of global transaction and its branches will be durable on coordinator side by WAL pattern.

We will publish a wiki page to show mechanism about this.
