### ISSUE TITLE
if there have two transactions,may I join the second in first?

### ISSUE THREAD

**Issue by aa3313322122** [alibaba/fescar#385]
for example , write account flow, first global transaction is not complete, but first local transaction  is fine, now the second transaction is come in,   if global transaction is failed, I wish the second transaction if failed too,  even if the second is success.
I think makes second join the first global transaction is the only way, so, can fescar do it? 
or it has any other solution?

**Comment by slievrly** [comment]
nest global transaction。
@GlobalTransactional
A(){
B();
} 
@GlobalTransactional
B(){}

**Comment by aa3313322122** [comment]
ok, I see ..join the step in global transaction so that the second request will know the first global transaction is not fine.
