### ISSUE TITLE
Spring cloud is not currently supported

### ISSUE THREAD

**Issue by xinglixin** [alibaba/fescar#39]
The use of spring cloud has become more and more extensive, support as soon as possible
// spring cloud的使用已经越来越广泛了，尽快支持哈

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by tiantao-2014** [comment]
什么时候能够支持，希望尽快哈

**Comment by Quiter2013** [comment]
怎样才能加入一起贡献点代码，已经磨拳搽掌了

**Comment by flystar32** [comment]
@Quiter2013 @tiantao-2014  you can refer to this issue and  repository, https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/303
