### ISSUE TITLE
Why are there restrictions on the database?

### ISSUE THREAD

**Issue by 1991wangliang** [alibaba/fescar#392]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
the sqlParser is different, and subsequent databases will be supported.

**Comment by 1991wangliang** [comment]
why not used p6spy?

**Comment by 1991wangliang** [comment]
fescar-robot that's a github plugin? so cool.

**Comment by rtj599** [comment]
different kind of DBMSs are not only different from sql statement,but also have different implementations of XA that have to do with transaction control of fescar.I recommend you to read souce code about how fescar support mysql.

**Comment by 1991wangliang** [comment]
yeah, i can read . but i think that will too tired.so many databases.
