### ISSUE TITLE
中国的开源，请用中文

### ISSUE THREAD

**Issue by zhuzhengwen1983** [alibaba/fescar#41]
我对语言没有歧视，但我认为，中国的开源产品就应该用中文文档。你们是想更多的中国公司用还是外国公司用？想想哪个更现实点。

**Comment by pguo65535** [comment]
别急... 中文文档正在准备过程中

**Comment by kingzuo** [comment]
希望不要烂尾

**Comment by jonwinters** [comment]
@kingzuo  维护是不可能维护的，这辈子都不可能好好维护的，维护技术业界的好名声又不会，只能靠开源出来一点东西然后烂尾维持一下啦。

**Comment by sharajava** [comment]
官网在建设中，文档（包括中文、英文）在发布过程中，很快会看到。
