### ISSUE TITLE
fescar-spring集成spring security报错

### ISSUE THREAD

**Issue by 408043749** [alibaba/fescar#432]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
集成springsecurity时报错，如下：
![image](https://user-images.githubusercontent.com/1967569/53064457-db7b2c00-3502-11e9-9170-599061b9ffff.png)

### Ⅱ. Describe what happened

  加入依赖：
        <dependency>
            <groupId>com.alibaba.fescar</groupId>
            <artifactId>fescar-spring</artifactId>
            <version>0.2.1</version>
        </dependency>
 集成springsecurity时报错

**Comment by slievrly** [comment]
@408043749 Too little information, can you share your use case?

**Comment by 408043749** [comment]
已解决
