### ISSUE TITLE
rollback sql fix

### ISSUE THREAD

**Issue by chenloong2046** [alibaba/fescar#459]
the samples rollback generate rollback sql:
UPDATE t_asset_assign SET desc = ?, status = ?, update_time = ?, update_user = ? WHERE id = ?;
reason is that the parameter ‘desc ’ is mysql keyword, suggest to add `` char on rollback sql parameter at AbstractUndoExecutor.buildUndoSQL()

**Comment by xingfudeshi** [comment]
Thanks for reporting.it should be a bug.i will fix it ASAP.

**Comment by slievrly** [comment]
> Thanks for reporting.it should be a bug.i will fix it ASAP.

where PR?

**Comment by xingfudeshi** [comment]
@slievrly PR made.
