### ISSUE TITLE
What's the working principle of FESCAR isolation level "READ-COMMITTED" 

### ISSUE THREAD

**Issue by rtj599** [alibaba/fescar#496]
I'd like to know how FESCAR implements "READ-COMMITTED". Here are some questions about this issue that I wonder most:
1.how to make the local committed data invisible while global tx is not committed?
2.If there are some other services using the same DB without management of FESCAR, will an operation of  local commit and global rollback lead DIRTY READ to other services?
3.What are the implementions of the core classes?

**Comment by slievrly** [comment]
@rtj599 
1. If all the modifications are left to the fescar management, then use select for update to RC
2. If not managed by fescar then unmanaged transactions will read uncommited
3. SelectForUpdateExecutor?

**Comment by rtj599** [comment]
thanks
