### ISSUE TITLE
Double check lock

### ISSUE THREAD

**Issue by 360CodeSafe** [alibaba/fescar#521]
您好：
我是360代码卫士团队的工作人员，在我们的开源项目检测计划中发现fescar中存在双重检查锁定缺陷。
com.alibaba.fescar.common.loader.EnhancedServiceLoader.java
![image](https://user-images.githubusercontent.com/39950310/53792223-1ef38280-3f66-11e9-81e8-48fa4e11c273.png)
代码在实现延迟初始化时操作时选择了双重检查锁定时这一较优处理，但在降低了开销的同时仍有可能出错。建议在此基础上为使用volatile关键字来修饰 foundFromCache，来保证在多线程环境中不会出错。

**Comment by gumandy** [comment]
foundFromCache is in stack space
