### ISSUE TITLE
Hardcoded file separator

### ISSUE THREAD

**Issue by 360CodeSafe** [alibaba/fescar#522]
您好：
我是360代码卫士团队的工作人员，在我们的开源项目检测计划中发现fescar中存在硬编码文件分隔符代码质量问题。
com.alibaba.fescar.server.session.SessionHolder.java 
![image](https://user-images.githubusercontent.com/39950310/53793169-3f244100-3f68-11e9-9e66-2a1bea20bd23.png)

路径分割符号问题，不同的操作系统不同。不应使用硬编码文件分隔符，而应使用语言库提供的独立于平台的API，如java.io.File.separator，也可以通过使用java.lang.System.getProperty("file.separator")来获取。

**Comment by xingfudeshi** [comment]
Thank you for informing us of this problem.I'll fix it soon.
