### ISSUE TITLE
GlobalTransactionScanner can't find @GlobalTransactional

### ISSUE THREAD

**Issue by CoderEugene** [alibaba/fescar#576]
### Issue Description

If I use `<aop:aspectj-autoproxy />`, then the aspect and @GlobalTransactional point to the same method, which will cause the GlobalTransactionalInterceptor fail to get @GlobalTransactional

### Describe what happened

```java

public interface ITest {

    void execute();
}

public class ITestImpl implements ITest {

    @GlobalTransactional
    @Override
    public void execute() {
    }
}

@Aspect
public class MyAspect {

    @Before("execution(* com.xx.ITestImpl.execute(..))")
    public void before(){
    }
}

```

### Describe what you expected to happen
forcing the use of cglib can solve this problem, but what is the reason for building a new AutoProxyCreator (GlobalTransactionScanner)?Is it better to use spring built-in, e.g. @annotation(com.xxx.GlobalTransactional) directly? Thx

**Comment by slievrly** [comment]
@CoderEugene please dingTalk ping me
