### ISSUE TITLE
Fescar supports org.apache.dubbo

### ISSUE THREAD

**Issue by 3EDCKenneth** [alibaba/fescar#599]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
开源的dubbo 和fescar不兼容，现在只支持com.alibaba.dubbo.
那个版本才能支持？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by 3EDCKenneth** [comment]
@slievrly   没明白， 能详细讲解下么?

**Comment by 3EDCKenneth** [comment]
我使用的是io.dubbo.springboot v1.0.0

**Comment by xingfudeshi** [comment]
In the fescar,there are two modules for supporting dubbo.which the dubbo module is used to support Apache Dubbo.and the dubbo-alibaba module is used to support Alibaba Dubbo.please refer the source code of Fescar for details.

**Comment by slievrly** [comment]
> In the fescar,there are two modules for supporting dubbo.which the dubbo module is used to support Apache Dubbo.and the dubbo-alibaba module is used to support Alibaba Dubbo.please refer the source code of Fescar for details.

good job
