### ISSUE TITLE
should we consider the impact of  using undo_log on the behavior of DB?

### ISSUE THREAD

**Issue by rtj599** [alibaba/fescar#604]
I think there is a preformance loss of db server by inserting,selecting,and deleting the undo log data when handling a large of business data, and cause extra hard disk space occupation temporary.So there should be a guidance or a warning or sth to remind users to know the impact and do some db optimization such as tablespace design and  more hard disk space application before using FESCAR,or do some optimization for FESCAR by desinging other ways to record undo log data.

**Comment by xingfudeshi** [comment]
Yes.you are right.there should be a guidance to let user know what's the requirement for running of fescar.and we'll consider your suggestion.
