### ISSUE TITLE
rollback problem of different DB

### ISSUE THREAD

**Issue by vikenlove** [alibaba/fescar#617]
hi everyone
  i have a question about fescar rollback for transcation 

 for this code ：
`	@Autowired
	private DemoFeignClient demoFeignClient;
	
	@Autowired
	private DemoFeignClient2 demoFeignClient2;
	@GlobalTransactional(timeoutMills = 300000, name = "spring-cloud-demo-tx")
	@GetMapping("/getdemo")
	public String demo() {
		
		// 调用A 服务  简单save  数据在A数据库的test表中
		Integer result = demoFeignClient.insertService("test",1);
		
		// 调用B 服务(B数据库中的 test表中)。报错测试A 服务回滚
		demoFeignClient2.saveService();
		
		System.out.println("this is -------port:9091");
		return "data";
	}`
the problem is  B service run fail, but A service can not rollback , it is still save success, 
please help me .and  i need other Configuration?

**Comment by slievrly** [comment]
Is fescar's starter referenced? Please print xid at the provider

**Comment by vikenlove** [comment]
@slievrly   i was imported fescar-starter to my project service A & B . i can print to xid in my service project A & B . bug it isn't still rollback ,

**Comment by xingfudeshi** [comment]
For resolving your problem.please create a github repo for your example.so we can debug it locally.

**Comment by vikenlove** [comment]
@xingfudeshi  i have find it  by  slievrly help ,it is  a bug for fescar . but i don't konw how to fixed it and waiting for fixed it by other fescar's developer

**Comment by xingfudeshi** [comment]
@vikenlove ok.will fix it later.

**Comment by vikenlove** [comment]
@xingfudeshi  which is version fixed it？ 0.4.0 GA？

**Comment by vikenlove** [comment]
ERROR 12172 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : eureka client is not register,do this operation had to be register!
2019-03-20 09:30:44.369 ERROR 12172 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : no available server to connect.
@xingfudeshi  does fescar‘s developer  not  fixed this bug at 0.4.0 version？

**Comment by slievrly** [comment]
@vikenlove please dingtalk ping  me。
