### ISSUE TITLE
Chinese document

### ISSUE THREAD

**Issue by zhangzhen894095789** [alibaba/fescar#640]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
please refer [https://github.com/alibaba/fescar/wiki/Home_Chinese](url)

**Comment by xingfudeshi** [comment]
I'll close this issue.if you have further question,please comment on this issue.thanks.
