### ISSUE TITLE
RmRpcClient no available server to connect & TmRpcClient no available server to connect

### ISSUE THREAD

**Issue by MrLiuFang** [alibaba/fescar#659]
fescar-server 配置 如下  启动正常
registry {
  # file 、nacos 、eureka、redis、zk
  type = "zk"

config {
  # file、nacos 、apollo、zk
  type = "file"

################################################################
/src/main/resources/   已添加 application.conf
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
}
service {
  #vgroup->rgroup
  vgroup_mapping.receivables = "localRgroup"
  #only support single node
  #localRgroup.grouplist = "120.79.42.224:9091"
  localRgroup.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
}
###############################################################

 java 程序报
2019-03-26 14:34:30.771 ERROR 11097 --- [imeoutChecker_1] c.a.f.c.ConfigFuture                     : config operation timeout,cost:5000 ms,op:GET,dataId:service.vgroup_mapping.spring-boot-dubbo
2019-03-26 14:34:30.771 ERROR 11097 --- [imeoutChecker_1] c.a.f.c.ConfigFuture                     : config operation timeout,cost:5000 ms,op:GET,dataId:service.vgroup_mapping.spring-boot-dubbo
2019-03-26 14:34:30.771 ERROR 11097 --- [imeoutChecker_1] c.a.f.c.r.n.RmRpcClient                  : no available server to connect.
2019-03-26 14:34:30.771 ERROR 11097 --- [imeoutChecker_1] c.a.f.c.r.n.TmRpcClient                  : no available server to connect.

请问这是什么问题？？？

**Comment by xingfudeshi** [comment]
Did you have the following files in your application or Fesacr-samples?
registry.conf
file.conf
Configuration should be consistent with Fescar server-side configuration.

**Comment by xingfudeshi** [comment]
I see you changed the group name to receivables 
`#vgroup->rgroup  

vgroup_mapping.**receivables** = "localRgroup"`
you have to make sure the new group name is consistent where it occurs

For example,if you want to change the name to my_test_tx_group
1.Fescar server side,the file.conf should be like:
service {
#vgroup->rgroup
vgroup_mapping.my_test_tx_group = "default"

...
}
2.Your application side,the file.conf should be like:
service {
#vgroup->rgroup
vgroup_mapping.my_test_tx_group = "default"

...
}
3.@GlobalTransactional(timeoutMills = 300000, name = "my_test_tx_group ")

**Comment by MrLiuFang** [comment]
问题解决.非常感谢 !感谢大牛们的无私奉献.
