### ISSUE TITLE
download fescar-develop source build not pass

### ISSUE THREAD

**Issue by jsbxyyx** [alibaba/fescar#664]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
the source build not pass
com.alibaba.fescar.core.service.ServiceManagerStaticConfigImpl.java on 66 line StringUtils.isEmpty method not found
branch: develop
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

your can use org.apache.commons.lang.StringUtils.isEmpty or com.alibaba.fescar.common.util.StringUtils.isNullOrEmpty

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others:

**Comment by xingfudeshi** [comment]
What commands do you use to build it?

**Comment by xingfudeshi** [comment]
try this
`mvn clean install -DskipTests -U`

**Comment by jsbxyyx** [comment]
@xingfudeshi mvn clean install -DskipTests

**Comment by xingfudeshi** [comment]
> @xingfudeshi mvn clean install -DskipTests

thanks for the feedback.i just used the commands you've provided to build Fescar.and it passed.
Please pull the latest source code,and try it again.

**Comment by xingfudeshi** [comment]
i will close this issue.if you have further question with build problem,please comment here,or open a new issue.thanks.
