### ISSUE TITLE
if we deosn't config IP when startup fescar server .maybe it return you computer'name .

### ISSUE THREAD

**Issue by vikenlove** [alibaba/fescar#672]
@xingfudeshi the source code NacosRegistryServiceImpl
` @override
public void register(InetSocketAddress address) throws Exception {
validAddress(address);

// address.getHostName() ? why isn't it addr.getHostAddress().
    getNamingInstance().registerInstance(PRO_SERVER_ADDR_KEY, address.getHostName(), address.getPort(),
        getClusterName());
}`
i don't know why does write it like this ? in the windows ,start up fescar.bat we will get address.getHostName() value is computer name ,but slievrly run code by IDE ,get value is IP address.

 this is my code InetAddress address = InetAddress.getLocalHost(); System.out.println(address.getHostName()); // your computer's name
So I get a value, this is my computer name. The source code for fescar is address.getHostName(). I think this should be addr.getHostAddress(). Because when starting the fescar server, we don't need conifg ip and fescar should automatically get our server IP.

**Comment by xingfudeshi** [comment]
duplicate issue #647
