### ISSUE TITLE
jdk version must 1.8+ ?

### ISSUE THREAD

**Issue by loooSwc** [alibaba/fescar#678]
like this,fescar's jdk version must 1.8+?
![20190328175105](https://user-images.githubusercontent.com/22002598/55147834-19164900-5182-11e9-9110-e0c293d3c851.png)

**Comment by xingfudeshi** [comment]
At least 1.8

**Comment by slievrly** [comment]
The jdk version that fescar relied on was 1.7, but nacos requires at least 1.8+.

**Comment by xingfudeshi** [comment]
i will close this issue.if you have further question about this issue,please comment here.thank you.
