### ISSUE TITLE
group name must be my_test_tx_group ?

### ISSUE THREAD

**Issue by Wizzercn** [alibaba/fescar#685]
Server-side configuration file changed to:

`vgroup_mapping.wk_nb_tx_group = "localRgroup"`

Client also uses  `wk_nb_tx_group`  group name,The client will not be able to connect to the service.

Use `my_test_tx_group` Can be connected normally.

**Comment by xingfudeshi** [comment]
which registry did you use?

**Comment by xingfudeshi** [comment]
The group name can be changed,just make sure the group name should be consistent.
For example,if you want to change the name to my_test_tx_group 
1.Fescar server side,the file.conf should be like:
service {  
 #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"  

...  
}
2.Your application side,the file.conf should be like:
service {  
 #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"  

...  
}
3.@GlobalTransactional(timeoutMills = 300000, name = "my_test_tx_group ")

**Comment by philoli11** [comment]
I also encountered this problem with the file registry. Did fescar-rm read the configuration information in the fescar-config package? If I modify the configuration in the fescar-config, the service will read the modified configuration.

**Comment by philoli11** [comment]
Modify the configuration file in the demo named file.config, otherwise the default configuration will be used.

**Comment by slievrly** [comment]
@xingfudeshi good job

**Comment by Wizzercn** [comment]
I see, maybe GlobalTransactional is missing the name attribute.
Thank you.

**Comment by xingfudeshi** [comment]
Also please pull the latest code.as we have fixed some problems.
