### ISSUE TITLE
[Feature] Please add test coverage and build result in the README

### ISSUE THREAD

**Issue by lovepoem** [alibaba/fescar#73]
Please add test coverage and build result 

Please see this sample：
https://github.com/lovepoem/codecov-travis-maven-junit4-example  or https://github.com/alibaba/dubbo

**Comment by sharajava** [comment]
👍 working on it. Thanks.

**Comment by mdjakirhasan** [comment]
Sir can you help me please

**Comment by lovepoem** [comment]
close via https://github.com/alibaba/fescar/pull/133
