### ISSUE TITLE
com.alibaba.druid.sql.ast.expr.SQLBetweenExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr

### ISSUE THREAD

**Issue by xusong** [alibaba/fescar#75]
jdbcTemplate.update("update itest2 set x=x+1 where id between 9 and 11 ");

throw an exception "com.alibaba.druid.sql.ast.expr.SQLBetweenExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr"

"id" is primarykey for table of itest2 , it is not support for "between" syntax ? ?

**Comment by sharajava** [comment]
Did it happen on MySQL?

If so it should be a bug. I will check it later. However, it will be great if you can share your fix with us.

👍

**Comment by xusong** [comment]
@sharajava 
now fix it like this

public class MySQLUpdateRecognizer extends BaseRecognizer implements SQLUpdateRecognizer {
	...
	//fix before -------------------
	@Override
    public String getWhereCondition() {
        SQLExpr where = ast.getWhere();
        if (where == null) {
            return "";
        }
        StringBuffer sb = new StringBuffer();
        MySqlOutputVisitor visitor = new MySqlOutputVisitor(sb);
        visitor.visit((SQLBinaryOpExpr) where);
        return sb.toString();
    }

	//fix after --------------------
	@Override
    public String getWhereCondition() {
        SQLExpr where = ast.getWhere();
        if (where == null) {
            return "";
        }
        StringBuffer sb = new StringBuffer();
        MySqlOutputVisitor visitor = new MySqlOutputVisitor(sb);
        if(where instanceof SQLBetweenExpr){
            visitor.visit((SQLBetweenExpr) where);
        }else if(where instanceof SQLInListExpr){
            visitor.visit((SQLInListExpr) where);
        }else{
            visitor.visit((SQLBinaryOpExpr) where);
        }
        return sb.toString();
    }
	...
}

but MySqlOutputVisitor have too many methods named visit, 
it can works but not a good plan
may be know druid then fix it at all

**Comment by sharajava** [comment]
Yes. Let's try to find a better way later. PR #412 was just merged.
