### ISSUE TITLE
FileTransactionStoreManager.WriteDataFileRunnable#saveHistory() method should not use File.renameTo() to save history

### ISSUE THREAD

**Issue by ykgarfield** [alibaba/fescar#92]
Now FileTransactionStoreManager.WriteDataFileRunnable#saveHistory() use `File.rename()` method to save history data.

```
private void saveHistory() throws IOException {
	...
	currDataFile.renameTo(new File(hisFullFileName));
}
```

But according java doc, the `File.rename()` is unreliable.In fact, I've had this problem before.For example Jetty bug: [Jetty bug due to File.rename method](https://bugs.eclipse.org/bugs/show_bug.cgi?id=466005)

It's better to use `Files#move()` method or any others ways.

**Comment by slievrly** [comment]
@ykgarfield  OK, I will try Files#move()
