### ISSUE TITLE
maven install error ：Failed to create assembly: Error adding file to archive: D:\open_project\fescar\distribution\NOTICE-BIN

### ISSUE THREAD

**Issue by heshouyou** [alibaba/fescar#93]
while maven install fescar project，it build fail.
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (make-assembly) on project fescar-distribution: Failed to create assembly: Error adding file to archive: D:\open_project\fescar\distribution\NOTICE-BIN -> [Help 1]

"fescar-distribution 0.1.0-SNAPSHOT " module is building fail.
so i find it lack “NOTICE-BIN”  file.

**Comment by slievrly** [comment]
Non repeatable，If the problem reappears, please paste maven exception and notice @slievrly

**Comment by slievrly** [comment]
make sure your local code up to date
